export const IOC_TOKENS = {
  USER_REPOSITORY: Symbol("USER_REPOSITORY"),
  CITY_REPOSITORY: Symbol("CITY_REPOSITORY"),
  HOME_REPOSITORY: Symbol("HOME_REPOSITORY"),
  DASHBOARD_REPOSITORY: Symbol("DASHBOARD_REPOSITORY"),
  BLOG_REPOSITORY: Symbol("BLOG_REPOSITORY"),
  COURSE_REPOSITORY: Symbol("COURSE_REPOSITORY"),
  CART_REPOSITORY: Symbol("CART_REPOSITORY"),
  ORDER_REPOSITORY: Symbol("ORDER_REPOSITORY"),
  LESSON_NOTE_REPOSITORY: Symbol('LESSON_NOTE_REPOSITORY'),
  CONTACT_REPOSITORY: Symbol("CONTACT_REPOSITORY"),
  EVENT_MANAGER: Symbol("EVENT_MANAGER"),
  EVENT_BUS: Symbol("EVENT_BUS"),
} as const;

export type IoCToken = (typeof IOC_TOKENS)[keyof typeof IOC_TOKENS];
