FROM node:22-alpine AS deps
WORKDIR /app

COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG APP_PORT=3000
ARG BACKEND_API_URL
ARG BACKEND_AUTH_LOGIN_PATH
ARG BACKEND_AUTH_LOGOUT_PATH
ARG BACKEND_AUTH_ME_PATH
ARG ACCESS_TOKEN_EMAIL
ARG ACCESS_TOKEN_PASSWORD
ARG PROXY_GUARD_SECRET
ARG PROXY_GUARD_TTL_SECONDS
ARG PROXY_GUARD_REFRESH_THRESHOLD_SECONDS
ARG USER_ACCESS_TOKEN_COOKIE_NAME
ARG USER_ACCESS_TOKEN_COOKIE_TTL_SECONDS
ARG AUTH_ACCESS_TOKEN_MAX_AGE
ARG AUTH_REFRESH_TOKEN_MAX_AGE
ARG NEXT_PUBLIC_BACKEND_PORT
ARG NEXT_PUBLIC_BACKEND_BASE_URL
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_RECAPTCHA_REGISTER_ACTION
ARG NEXT_PUBLIC_RECAPTCHA_CONTACT_ACTION

ENV APP_PORT=${APP_PORT}
ENV PORT=${APP_PORT}
ENV BACKEND_API_URL=${BACKEND_API_URL}
ENV BACKEND_AUTH_LOGIN_PATH=${BACKEND_AUTH_LOGIN_PATH}
ENV BACKEND_AUTH_LOGOUT_PATH=${BACKEND_AUTH_LOGOUT_PATH}
ENV BACKEND_AUTH_ME_PATH=${BACKEND_AUTH_ME_PATH}
ENV ACCESS_TOKEN_EMAIL=${ACCESS_TOKEN_EMAIL}
ENV ACCESS_TOKEN_PASSWORD=${ACCESS_TOKEN_PASSWORD}
ENV PROXY_GUARD_SECRET=${PROXY_GUARD_SECRET}
ENV PROXY_GUARD_TTL_SECONDS=${PROXY_GUARD_TTL_SECONDS}
ENV PROXY_GUARD_REFRESH_THRESHOLD_SECONDS=${PROXY_GUARD_REFRESH_THRESHOLD_SECONDS}
ENV USER_ACCESS_TOKEN_COOKIE_NAME=${USER_ACCESS_TOKEN_COOKIE_NAME}
ENV USER_ACCESS_TOKEN_COOKIE_TTL_SECONDS=${USER_ACCESS_TOKEN_COOKIE_TTL_SECONDS}
ENV AUTH_ACCESS_TOKEN_MAX_AGE=${AUTH_ACCESS_TOKEN_MAX_AGE}
ENV AUTH_REFRESH_TOKEN_MAX_AGE=${AUTH_REFRESH_TOKEN_MAX_AGE}
ENV NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
ENV NEXT_PUBLIC_BACKEND_BASE_URL=${NEXT_PUBLIC_BACKEND_BASE_URL}
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
ENV NEXT_PUBLIC_RECAPTCHA_REGISTER_ACTION=${NEXT_PUBLIC_RECAPTCHA_REGISTER_ACTION}
ENV NEXT_PUBLIC_RECAPTCHA_CONTACT_ACTION=${NEXT_PUBLIC_RECAPTCHA_CONTACT_ACTION}

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ARG APP_PORT=3000
ARG BACKEND_API_URL
ARG BACKEND_AUTH_LOGIN_PATH
ARG BACKEND_AUTH_LOGOUT_PATH
ARG BACKEND_AUTH_ME_PATH
ARG ACCESS_TOKEN_EMAIL
ARG ACCESS_TOKEN_PASSWORD
ARG PROXY_GUARD_SECRET
ARG PROXY_GUARD_TTL_SECONDS
ARG PROXY_GUARD_REFRESH_THRESHOLD_SECONDS
ARG USER_ACCESS_TOKEN_COOKIE_NAME
ARG USER_ACCESS_TOKEN_COOKIE_TTL_SECONDS
ARG AUTH_ACCESS_TOKEN_MAX_AGE
ARG AUTH_REFRESH_TOKEN_MAX_AGE
ARG NEXT_PUBLIC_BACKEND_PORT
ARG NEXT_PUBLIC_BACKEND_BASE_URL
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_RECAPTCHA_REGISTER_ACTION
ARG NEXT_PUBLIC_RECAPTCHA_CONTACT_ACTION

ENV APP_PORT=${APP_PORT}
ENV PORT=${APP_PORT}
ENV BACKEND_API_URL=${BACKEND_API_URL}
ENV BACKEND_AUTH_LOGIN_PATH=${BACKEND_AUTH_LOGIN_PATH}
ENV BACKEND_AUTH_LOGOUT_PATH=${BACKEND_AUTH_LOGOUT_PATH}
ENV BACKEND_AUTH_ME_PATH=${BACKEND_AUTH_ME_PATH}
ENV ACCESS_TOKEN_EMAIL=${ACCESS_TOKEN_EMAIL}
ENV ACCESS_TOKEN_PASSWORD=${ACCESS_TOKEN_PASSWORD}
ENV PROXY_GUARD_SECRET=${PROXY_GUARD_SECRET}
ENV PROXY_GUARD_TTL_SECONDS=${PROXY_GUARD_TTL_SECONDS}
ENV PROXY_GUARD_REFRESH_THRESHOLD_SECONDS=${PROXY_GUARD_REFRESH_THRESHOLD_SECONDS}
ENV USER_ACCESS_TOKEN_COOKIE_NAME=${USER_ACCESS_TOKEN_COOKIE_NAME}
ENV USER_ACCESS_TOKEN_COOKIE_TTL_SECONDS=${USER_ACCESS_TOKEN_COOKIE_TTL_SECONDS}
ENV AUTH_ACCESS_TOKEN_MAX_AGE=${AUTH_ACCESS_TOKEN_MAX_AGE}
ENV AUTH_REFRESH_TOKEN_MAX_AGE=${AUTH_REFRESH_TOKEN_MAX_AGE}
ENV NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
ENV NEXT_PUBLIC_BACKEND_BASE_URL=${NEXT_PUBLIC_BACKEND_BASE_URL}
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
ENV NEXT_PUBLIC_RECAPTCHA_REGISTER_ACTION=${NEXT_PUBLIC_RECAPTCHA_REGISTER_ACTION}
ENV NEXT_PUBLIC_RECAPTCHA_CONTACT_ACTION=${NEXT_PUBLIC_RECAPTCHA_CONTACT_ACTION}

COPY package*.json ./
COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./next.config.ts

EXPOSE ${APP_PORT}
CMD ["sh", "-c", "npm run start -- --port ${APP_PORT}"]
